#include "../../services.h"
#include "../../core/bufferStringStream.h"
#include "gl.h"

#ifdef ARPHEG_PLATFORM_WIN32

//function loading
struct Loader {
	int major,minor;
	void (*onError)(const char*);
	core::bufferStringStream::Formatter formatter;
	
	void* load(const char* name){
#ifdef ARPHEG_PLATFORM_WIN32
		void* proc = (void*)wglGetProcAddress(name);
#endif
		if(!proc){
			formatter.allocator.reset();
			core::bufferStringStream::printf(formatter,"Failed to load OpenGL core function '%s' - the application may not behave correctly!\n  Please update your graphics card's drivers.",name);
			services::logging()->warning(core::bufferStringStream::asCString(formatter));
		}
		if(!proc && onError) onError(name);
		return proc;
	}
};

#define F(f,T) f = (T) loader.load(#f);

void rendering::loadOpenGLCore(int version,void (*onError)(const char*)) {
	Loader loader;
    loader.major = version / 10;
    loader.minor = version % 10;
	loader.onError = onError;

/*#ifndef ARPHEG_PLATFORM_WIN32
    if (version >= 10) {
        glCullFace = (PFNGLCULLFACEPROC) loader.load("glCullFace");
        glFrontFace = (PFNGLFRONTFACEPROC) loader.load("glFrontFace");
        glHint = (PFNGLHINTPROC) loader.load("glHint");
        glLineWidth = (PFNGLLINEWIDTHPROC) loader.load("glLineWidth");
        glPointSize = (PFNGLPOINTSIZEPROC) loader.load("glPointSize");
        glPolygonMode = (PFNGLPOLYGONMODEPROC) loader.load("glPolygonMode");
        glScissor = (PFNGLSCISSORPROC) loader.load("glScissor");
        glTexParameterf = (PFNGLTEXPARAMETERFPROC) loader.load("glTexParameterf");
        glTexParameterfv = (PFNGLTEXPARAMETERFVPROC) loader.load("glTexParameterfv");
        glTexParameteri = (PFNGLTEXPARAMETERIPROC) loader.load("glTexParameteri");
        glTexParameteriv = (PFNGLTEXPARAMETERIVPROC) loader.load("glTexParameteriv");
        glTexImage1D = (PFNGLTEXIMAGE1DPROC) loader.load("glTexImage1D");
        glTexImage2D = (PFNGLTEXIMAGE2DPROC) loader.load("glTexImage2D");
        glDrawBuffer = (PFNGLDRAWBUFFERPROC) loader.load("glDrawBuffer");
        glClear = (PFNGLCLEARPROC) loader.load("glClear");
        glClearColor = (PFNGLCLEARCOLORPROC) loader.load("glClearColor");
        glClearStencil = (PFNGLCLEARSTENCILPROC) loader.load("glClearStencil");
        glClearDepth = (PFNGLCLEARDEPTHPROC) loader.load("glClearDepth");
        glStencilMask = (PFNGLSTENCILMASKPROC) loader.load("glStencilMask");
        glColorMask = (PFNGLCOLORMASKPROC) loader.load("glColorMask");
        glDepthMask = (PFNGLDEPTHMASKPROC) loader.load("glDepthMask");
        glDisable = (PFNGLDISABLEPROC) loader.load("glDisable");
        glEnable = (PFNGLENABLEPROC) loader.load("glEnable");
        glFinish = (PFNGLFINISHPROC) loader.load("glFinish");
        glFlush = (PFNGLFLUSHPROC) loader.load("glFlush");
        glBlendFunc = (PFNGLBLENDFUNCPROC) loader.load("glBlendFunc");
        glLogicOp = (PFNGLLOGICOPPROC) loader.load("glLogicOp");
        glStencilFunc = (PFNGLSTENCILFUNCPROC) loader.load("glStencilFunc");
        glStencilOp = (PFNGLSTENCILOPPROC) loader.load("glStencilOp");
        glDepthFunc = (PFNGLDEPTHFUNCPROC) loader.load("glDepthFunc");
        glPixelStoref = (PFNGLPIXELSTOREFPROC) loader.load("glPixelStoref");
        glPixelStorei = (PFNGLPIXELSTOREIPROC) loader.load("glPixelStorei");
        glReadBuffer = (PFNGLREADBUFFERPROC) loader.load("glReadBuffer");
        glReadPixels = (PFNGLREADPIXELSPROC) loader.load("glReadPixels");
        glGetBooleanv = (PFNGLGETBOOLEANVPROC) loader.load("glGetBooleanv");
        glGetDoublev = (PFNGLGETDOUBLEVPROC) loader.load("glGetDoublev");
        glGetError = (PFNGLGETERRORPROC) loader.load("glGetError");
        glGetFloatv = (PFNGLGETFLOATVPROC) loader.load("glGetFloatv");
        glGetIntegerv = (PFNGLGETINTEGERVPROC) loader.load("glGetIntegerv");
        glGetString = (PFNGLGETSTRINGPROC) loader.load("glGetString");
        glGetTexImage = (PFNGLGETTEXIMAGEPROC) loader.load("glGetTexImage");
        glGetTexParameterfv = (PFNGLGETTEXPARAMETERFVPROC) loader.load("glGetTexParameterfv");
        glGetTexParameteriv = (PFNGLGETTEXPARAMETERIVPROC) loader.load("glGetTexParameteriv");
        glGetTexLevelParameterfv = (PFNGLGETTEXLEVELPARAMETERFVPROC) loader.load("glGetTexLevelParameterfv");
        glGetTexLevelParameteriv = (PFNGLGETTEXLEVELPARAMETERIVPROC) loader.load("glGetTexLevelParameteriv");
        glIsEnabled = (PFNGLISENABLEDPROC) loader.load("glIsEnabled");
        glDepthRange = (PFNGLDEPTHRANGEPROC) loader.load("glDepthRange");
        glViewport = (PFNGLVIEWPORTPROC) loader.load("glViewport");
    }
    if (version >= 11) {
        glDrawArrays = (PFNGLDRAWARRAYSPROC) loader.load("glDrawArrays");
        glDrawElements = (PFNGLDRAWELEMENTSPROC) loader.load("glDrawElements");
        glGetPointerv = (PFNGLGETPOINTERVPROC) loader.load("glGetPointerv");
        glPolygonOffset = (PFNGLPOLYGONOFFSETPROC) loader.load("glPolygonOffset");
        glCopyTexImage1D = (PFNGLCOPYTEXIMAGE1DPROC) loader.load("glCopyTexImage1D");
        glCopyTexImage2D = (PFNGLCOPYTEXIMAGE2DPROC) loader.load("glCopyTexImage2D");
        glCopyTexSubImage1D = (PFNGLCOPYTEXSUBIMAGE1DPROC) loader.load("glCopyTexSubImage1D");
        glCopyTexSubImage2D = (PFNGLCOPYTEXSUBIMAGE2DPROC) loader.load("glCopyTexSubImage2D");
        glTexSubImage1D = (PFNGLTEXSUBIMAGE1DPROC) loader.load("glTexSubImage1D");
        glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC) loader.load("glTexSubImage2D");
        glBindTexture = (PFNGLBINDTEXTUREPROC) loader.load("glBindTexture");
        glDeleteTextures = (PFNGLDELETETEXTURESPROC) loader.load("glDeleteTextures");
        glGenTextures = (PFNGLGENTEXTURESPROC) loader.load("glGenTextures");
        glIsTexture = (PFNGLISTEXTUREPROC) loader.load("glIsTexture");
    }
#endif*/
    if (version >= 12) {
        glBlendColor = (PFNGLBLENDCOLORPROC) loader.load("glBlendColor");
        glBlendEquation = (PFNGLBLENDEQUATIONPROC) loader.load("glBlendEquation");
        glDrawRangeElements = (PFNGLDRAWRANGEELEMENTSPROC) loader.load("glDrawRangeElements");
        glTexImage3D = (PFNGLTEXIMAGE3DPROC) loader.load("glTexImage3D");
        glTexSubImage3D = (PFNGLTEXSUBIMAGE3DPROC) loader.load("glTexSubImage3D");
        glCopyTexSubImage3D = (PFNGLCOPYTEXSUBIMAGE3DPROC) loader.load("glCopyTexSubImage3D");
    }
    if (version >= 13) {
        glActiveTexture = (PFNGLACTIVETEXTUREPROC) loader.load("glActiveTexture");
        glSampleCoverage = (PFNGLSAMPLECOVERAGEPROC) loader.load("glSampleCoverage");
        glCompressedTexImage3D = (PFNGLCOMPRESSEDTEXIMAGE3DPROC) loader.load("glCompressedTexImage3D");
        glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC) loader.load("glCompressedTexImage2D");
        glCompressedTexImage1D = (PFNGLCOMPRESSEDTEXIMAGE1DPROC) loader.load("glCompressedTexImage1D");
        glCompressedTexSubImage3D = (PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC) loader.load("glCompressedTexSubImage3D");
        glCompressedTexSubImage2D = (PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC) loader.load("glCompressedTexSubImage2D");
        glCompressedTexSubImage1D = (PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC) loader.load("glCompressedTexSubImage1D");
        glGetCompressedTexImage = (PFNGLGETCOMPRESSEDTEXIMAGEPROC) loader.load("glGetCompressedTexImage");
    }
    if (version >= 14) {
        glBlendFuncSeparate = (PFNGLBLENDFUNCSEPARATEPROC) loader.load("glBlendFuncSeparate");
        glMultiDrawArrays = (PFNGLMULTIDRAWARRAYSPROC) loader.load("glMultiDrawArrays");
        glMultiDrawElements = (PFNGLMULTIDRAWELEMENTSPROC) loader.load("glMultiDrawElements");
        glPointParameterf = (PFNGLPOINTPARAMETERFPROC) loader.load("glPointParameterf");
        glPointParameterfv = (PFNGLPOINTPARAMETERFVPROC) loader.load("glPointParameterfv");
        glPointParameteri = (PFNGLPOINTPARAMETERIPROC) loader.load("glPointParameteri");
        glPointParameteriv = (PFNGLPOINTPARAMETERIVPROC) loader.load("glPointParameteriv");
    }
    if (version >= 15) {
        glGenQueries = (PFNGLGENQUERIESPROC) loader.load("glGenQueries");
        glDeleteQueries = (PFNGLDELETEQUERIESPROC) loader.load("glDeleteQueries");
        glIsQuery = (PFNGLISQUERYPROC) loader.load("glIsQuery");
        glBeginQuery = (PFNGLBEGINQUERYPROC) loader.load("glBeginQuery");
        glEndQuery = (PFNGLENDQUERYPROC) loader.load("glEndQuery");
        glGetQueryiv = (PFNGLGETQUERYIVPROC) loader.load("glGetQueryiv");
        glGetQueryObjectiv = (PFNGLGETQUERYOBJECTIVPROC) loader.load("glGetQueryObjectiv");
        glGetQueryObjectuiv = (PFNGLGETQUERYOBJECTUIVPROC) loader.load("glGetQueryObjectuiv");
        glBindBuffer = (PFNGLBINDBUFFERPROC) loader.load("glBindBuffer");
        glDeleteBuffers = (PFNGLDELETEBUFFERSPROC) loader.load("glDeleteBuffers");
        glGenBuffers = (PFNGLGENBUFFERSPROC) loader.load("glGenBuffers");
        glIsBuffer = (PFNGLISBUFFERPROC) loader.load("glIsBuffer");
        glBufferData = (PFNGLBUFFERDATAPROC) loader.load("glBufferData");
        glBufferSubData = (PFNGLBUFFERSUBDATAPROC) loader.load("glBufferSubData");
        glGetBufferSubData = (PFNGLGETBUFFERSUBDATAPROC) loader.load("glGetBufferSubData");
        glMapBuffer = (PFNGLMAPBUFFERPROC) loader.load("glMapBuffer");
        glUnmapBuffer = (PFNGLUNMAPBUFFERPROC) loader.load("glUnmapBuffer");
        glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC) loader.load("glGetBufferParameteriv");
        glGetBufferPointerv = (PFNGLGETBUFFERPOINTERVPROC) loader.load("glGetBufferPointerv");
    }
    if (version >= 20) {
        glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC) loader.load("glBlendEquationSeparate");
        glDrawBuffers = (PFNGLDRAWBUFFERSPROC) loader.load("glDrawBuffers");
        glStencilOpSeparate = (PFNGLSTENCILOPSEPARATEPROC) loader.load("glStencilOpSeparate");
        glStencilFuncSeparate = (PFNGLSTENCILFUNCSEPARATEPROC) loader.load("glStencilFuncSeparate");
        glStencilMaskSeparate = (PFNGLSTENCILMASKSEPARATEPROC) loader.load("glStencilMaskSeparate");
        glAttachShader = (PFNGLATTACHSHADERPROC) loader.load("glAttachShader");
        glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC) loader.load("glBindAttribLocation");
        glCompileShader = (PFNGLCOMPILESHADERPROC) loader.load("glCompileShader");
        glCreateProgram = (PFNGLCREATEPROGRAMPROC) loader.load("glCreateProgram");
        glCreateShader = (PFNGLCREATESHADERPROC) loader.load("glCreateShader");
        glDeleteProgram = (PFNGLDELETEPROGRAMPROC) loader.load("glDeleteProgram");
        glDeleteShader = (PFNGLDELETESHADERPROC) loader.load("glDeleteShader");
        glDetachShader = (PFNGLDETACHSHADERPROC) loader.load("glDetachShader");
        glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC) loader.load("glDisableVertexAttribArray");
        glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC) loader.load("glEnableVertexAttribArray");
        glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC) loader.load("glGetActiveAttrib");
        glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC) loader.load("glGetActiveUniform");
        glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC) loader.load("glGetAttachedShaders");
        glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC) loader.load("glGetAttribLocation");
        glGetProgramiv = (PFNGLGETPROGRAMIVPROC) loader.load("glGetProgramiv");
        glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC) loader.load("glGetProgramInfoLog");
        glGetShaderiv = (PFNGLGETSHADERIVPROC) loader.load("glGetShaderiv");
        glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC) loader.load("glGetShaderInfoLog");
        glGetShaderSource = (PFNGLGETSHADERSOURCEPROC) loader.load("glGetShaderSource");
        glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC) loader.load("glGetUniformLocation");
        glGetUniformfv = (PFNGLGETUNIFORMFVPROC) loader.load("glGetUniformfv");
        glGetUniformiv = (PFNGLGETUNIFORMIVPROC) loader.load("glGetUniformiv");
        glGetVertexAttribdv = (PFNGLGETVERTEXATTRIBDVPROC) loader.load("glGetVertexAttribdv");
        glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC) loader.load("glGetVertexAttribfv");
        glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC) loader.load("glGetVertexAttribiv");
        glGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC) loader.load("glGetVertexAttribPointerv");
        glIsProgram = (PFNGLISPROGRAMPROC) loader.load("glIsProgram");
        glIsShader = (PFNGLISSHADERPROC) loader.load("glIsShader");
        glLinkProgram = (PFNGLLINKPROGRAMPROC) loader.load("glLinkProgram");
        glShaderSource = (PFNGLSHADERSOURCEPROC) loader.load("glShaderSource");
        glUseProgram = (PFNGLUSEPROGRAMPROC) loader.load("glUseProgram");
        glUniform1f = (PFNGLUNIFORM1FPROC) loader.load("glUniform1f");
        glUniform2f = (PFNGLUNIFORM2FPROC) loader.load("glUniform2f");
        glUniform3f = (PFNGLUNIFORM3FPROC) loader.load("glUniform3f");
        glUniform4f = (PFNGLUNIFORM4FPROC) loader.load("glUniform4f");
        glUniform1i = (PFNGLUNIFORM1IPROC) loader.load("glUniform1i");
        glUniform2i = (PFNGLUNIFORM2IPROC) loader.load("glUniform2i");
        glUniform3i = (PFNGLUNIFORM3IPROC) loader.load("glUniform3i");
        glUniform4i = (PFNGLUNIFORM4IPROC) loader.load("glUniform4i");
        glUniform1fv = (PFNGLUNIFORM1FVPROC) loader.load("glUniform1fv");
        glUniform2fv = (PFNGLUNIFORM2FVPROC) loader.load("glUniform2fv");
        glUniform3fv = (PFNGLUNIFORM3FVPROC) loader.load("glUniform3fv");
        glUniform4fv = (PFNGLUNIFORM4FVPROC) loader.load("glUniform4fv");
        glUniform1iv = (PFNGLUNIFORM1IVPROC) loader.load("glUniform1iv");
        glUniform2iv = (PFNGLUNIFORM2IVPROC) loader.load("glUniform2iv");
        glUniform3iv = (PFNGLUNIFORM3IVPROC) loader.load("glUniform3iv");
        glUniform4iv = (PFNGLUNIFORM4IVPROC) loader.load("glUniform4iv");
        glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC) loader.load("glUniformMatrix2fv");
        glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC) loader.load("glUniformMatrix3fv");
        glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC) loader.load("glUniformMatrix4fv");
        glValidateProgram = (PFNGLVALIDATEPROGRAMPROC) loader.load("glValidateProgram");
        glVertexAttrib1d = (PFNGLVERTEXATTRIB1DPROC) loader.load("glVertexAttrib1d");
        glVertexAttrib1dv = (PFNGLVERTEXATTRIB1DVPROC) loader.load("glVertexAttrib1dv");
        glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC) loader.load("glVertexAttrib1f");
        glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC) loader.load("glVertexAttrib1fv");
        glVertexAttrib1s = (PFNGLVERTEXATTRIB1SPROC) loader.load("glVertexAttrib1s");
        glVertexAttrib1sv = (PFNGLVERTEXATTRIB1SVPROC) loader.load("glVertexAttrib1sv");
        glVertexAttrib2d = (PFNGLVERTEXATTRIB2DPROC) loader.load("glVertexAttrib2d");
        glVertexAttrib2dv = (PFNGLVERTEXATTRIB2DVPROC) loader.load("glVertexAttrib2dv");
        glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC) loader.load("glVertexAttrib2f");
        glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC) loader.load("glVertexAttrib2fv");
        glVertexAttrib2s = (PFNGLVERTEXATTRIB2SPROC) loader.load("glVertexAttrib2s");
        glVertexAttrib2sv = (PFNGLVERTEXATTRIB2SVPROC) loader.load("glVertexAttrib2sv");
        glVertexAttrib3d = (PFNGLVERTEXATTRIB3DPROC) loader.load("glVertexAttrib3d");
        glVertexAttrib3dv = (PFNGLVERTEXATTRIB3DVPROC) loader.load("glVertexAttrib3dv");
        glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC) loader.load("glVertexAttrib3f");
        glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC) loader.load("glVertexAttrib3fv");
        glVertexAttrib3s = (PFNGLVERTEXATTRIB3SPROC) loader.load("glVertexAttrib3s");
        glVertexAttrib3sv = (PFNGLVERTEXATTRIB3SVPROC) loader.load("glVertexAttrib3sv");
        glVertexAttrib4Nbv = (PFNGLVERTEXATTRIB4NBVPROC) loader.load("glVertexAttrib4Nbv");
        glVertexAttrib4Niv = (PFNGLVERTEXATTRIB4NIVPROC) loader.load("glVertexAttrib4Niv");
        glVertexAttrib4Nsv = (PFNGLVERTEXATTRIB4NSVPROC) loader.load("glVertexAttrib4Nsv");
        glVertexAttrib4Nub = (PFNGLVERTEXATTRIB4NUBPROC) loader.load("glVertexAttrib4Nub");
        glVertexAttrib4Nubv = (PFNGLVERTEXATTRIB4NUBVPROC) loader.load("glVertexAttrib4Nubv");
        glVertexAttrib4Nuiv = (PFNGLVERTEXATTRIB4NUIVPROC) loader.load("glVertexAttrib4Nuiv");
        glVertexAttrib4Nusv = (PFNGLVERTEXATTRIB4NUSVPROC) loader.load("glVertexAttrib4Nusv");
        glVertexAttrib4bv = (PFNGLVERTEXATTRIB4BVPROC) loader.load("glVertexAttrib4bv");
        glVertexAttrib4d = (PFNGLVERTEXATTRIB4DPROC) loader.load("glVertexAttrib4d");
        glVertexAttrib4dv = (PFNGLVERTEXATTRIB4DVPROC) loader.load("glVertexAttrib4dv");
        glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC) loader.load("glVertexAttrib4f");
        glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC) loader.load("glVertexAttrib4fv");
        glVertexAttrib4iv = (PFNGLVERTEXATTRIB4IVPROC) loader.load("glVertexAttrib4iv");
        glVertexAttrib4s = (PFNGLVERTEXATTRIB4SPROC) loader.load("glVertexAttrib4s");
        glVertexAttrib4sv = (PFNGLVERTEXATTRIB4SVPROC) loader.load("glVertexAttrib4sv");
        glVertexAttrib4ubv = (PFNGLVERTEXATTRIB4UBVPROC) loader.load("glVertexAttrib4ubv");
        glVertexAttrib4uiv = (PFNGLVERTEXATTRIB4UIVPROC) loader.load("glVertexAttrib4uiv");
        glVertexAttrib4usv = (PFNGLVERTEXATTRIB4USVPROC) loader.load("glVertexAttrib4usv");
        glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC) loader.load("glVertexAttribPointer");
    }
    if (version >= 21) {
        glUniformMatrix2x3fv = (PFNGLUNIFORMMATRIX2X3FVPROC) loader.load("glUniformMatrix2x3fv");
        glUniformMatrix3x2fv = (PFNGLUNIFORMMATRIX3X2FVPROC) loader.load("glUniformMatrix3x2fv");
        glUniformMatrix2x4fv = (PFNGLUNIFORMMATRIX2X4FVPROC) loader.load("glUniformMatrix2x4fv");
        glUniformMatrix4x2fv = (PFNGLUNIFORMMATRIX4X2FVPROC) loader.load("glUniformMatrix4x2fv");
        glUniformMatrix3x4fv = (PFNGLUNIFORMMATRIX3X4FVPROC) loader.load("glUniformMatrix3x4fv");
        glUniformMatrix4x3fv = (PFNGLUNIFORMMATRIX4X3FVPROC) loader.load("glUniformMatrix4x3fv");
    }
    if (version >= 30) {
        glColorMaski = (PFNGLCOLORMASKIPROC) loader.load("glColorMaski");
        glGetBooleani_v = (PFNGLGETBOOLEANI_VPROC) loader.load("glGetBooleani_v");
        glGetIntegeri_v = (PFNGLGETINTEGERI_VPROC) loader.load("glGetIntegeri_v");
        glEnablei = (PFNGLENABLEIPROC) loader.load("glEnablei");
        glDisablei = (PFNGLDISABLEIPROC) loader.load("glDisablei");
        glIsEnabledi = (PFNGLISENABLEDIPROC) loader.load("glIsEnabledi");
        glBeginTransformFeedback = (PFNGLBEGINTRANSFORMFEEDBACKPROC) loader.load("glBeginTransformFeedback");
        glEndTransformFeedback = (PFNGLENDTRANSFORMFEEDBACKPROC) loader.load("glEndTransformFeedback");
        glBindBufferRange = (PFNGLBINDBUFFERRANGEPROC) loader.load("glBindBufferRange");
        glBindBufferBase = (PFNGLBINDBUFFERBASEPROC) loader.load("glBindBufferBase");
        glTransformFeedbackVaryings = (PFNGLTRANSFORMFEEDBACKVARYINGSPROC) loader.load("glTransformFeedbackVaryings");
        glGetTransformFeedbackVarying = (PFNGLGETTRANSFORMFEEDBACKVARYINGPROC) loader.load("glGetTransformFeedbackVarying");
        glClampColor = (PFNGLCLAMPCOLORPROC) loader.load("glClampColor");
        glBeginConditionalRender = (PFNGLBEGINCONDITIONALRENDERPROC) loader.load("glBeginConditionalRender");
        glEndConditionalRender = (PFNGLENDCONDITIONALRENDERPROC) loader.load("glEndConditionalRender");
        glVertexAttribIPointer = (PFNGLVERTEXATTRIBIPOINTERPROC) loader.load("glVertexAttribIPointer");
        glGetVertexAttribIiv = (PFNGLGETVERTEXATTRIBIIVPROC) loader.load("glGetVertexAttribIiv");
        glGetVertexAttribIuiv = (PFNGLGETVERTEXATTRIBIUIVPROC) loader.load("glGetVertexAttribIuiv");
        glVertexAttribI1i = (PFNGLVERTEXATTRIBI1IPROC) loader.load("glVertexAttribI1i");
        glVertexAttribI2i = (PFNGLVERTEXATTRIBI2IPROC) loader.load("glVertexAttribI2i");
        glVertexAttribI3i = (PFNGLVERTEXATTRIBI3IPROC) loader.load("glVertexAttribI3i");
        glVertexAttribI4i = (PFNGLVERTEXATTRIBI4IPROC) loader.load("glVertexAttribI4i");
        glVertexAttribI1ui = (PFNGLVERTEXATTRIBI1UIPROC) loader.load("glVertexAttribI1ui");
        glVertexAttribI2ui = (PFNGLVERTEXATTRIBI2UIPROC) loader.load("glVertexAttribI2ui");
        glVertexAttribI3ui = (PFNGLVERTEXATTRIBI3UIPROC) loader.load("glVertexAttribI3ui");
        glVertexAttribI4ui = (PFNGLVERTEXATTRIBI4UIPROC) loader.load("glVertexAttribI4ui");
        glVertexAttribI1iv = (PFNGLVERTEXATTRIBI1IVPROC) loader.load("glVertexAttribI1iv");
        glVertexAttribI2iv = (PFNGLVERTEXATTRIBI2IVPROC) loader.load("glVertexAttribI2iv");
        glVertexAttribI3iv = (PFNGLVERTEXATTRIBI3IVPROC) loader.load("glVertexAttribI3iv");
        glVertexAttribI4iv = (PFNGLVERTEXATTRIBI4IVPROC) loader.load("glVertexAttribI4iv");
        glVertexAttribI1uiv = (PFNGLVERTEXATTRIBI1UIVPROC) loader.load("glVertexAttribI1uiv");
        glVertexAttribI2uiv = (PFNGLVERTEXATTRIBI2UIVPROC) loader.load("glVertexAttribI2uiv");
        glVertexAttribI3uiv = (PFNGLVERTEXATTRIBI3UIVPROC) loader.load("glVertexAttribI3uiv");
        glVertexAttribI4uiv = (PFNGLVERTEXATTRIBI4UIVPROC) loader.load("glVertexAttribI4uiv");
        glVertexAttribI4bv = (PFNGLVERTEXATTRIBI4BVPROC) loader.load("glVertexAttribI4bv");
        glVertexAttribI4sv = (PFNGLVERTEXATTRIBI4SVPROC) loader.load("glVertexAttribI4sv");
        glVertexAttribI4ubv = (PFNGLVERTEXATTRIBI4UBVPROC) loader.load("glVertexAttribI4ubv");
        glVertexAttribI4usv = (PFNGLVERTEXATTRIBI4USVPROC) loader.load("glVertexAttribI4usv");
        glGetUniformuiv = (PFNGLGETUNIFORMUIVPROC) loader.load("glGetUniformuiv");
        glBindFragDataLocation = (PFNGLBINDFRAGDATALOCATIONPROC) loader.load("glBindFragDataLocation");
        glGetFragDataLocation = (PFNGLGETFRAGDATALOCATIONPROC) loader.load("glGetFragDataLocation");
        glUniform1ui = (PFNGLUNIFORM1UIPROC) loader.load("glUniform1ui");
        glUniform2ui = (PFNGLUNIFORM2UIPROC) loader.load("glUniform2ui");
        glUniform3ui = (PFNGLUNIFORM3UIPROC) loader.load("glUniform3ui");
        glUniform4ui = (PFNGLUNIFORM4UIPROC) loader.load("glUniform4ui");
        glUniform1uiv = (PFNGLUNIFORM1UIVPROC) loader.load("glUniform1uiv");
        glUniform2uiv = (PFNGLUNIFORM2UIVPROC) loader.load("glUniform2uiv");
        glUniform3uiv = (PFNGLUNIFORM3UIVPROC) loader.load("glUniform3uiv");
        glUniform4uiv = (PFNGLUNIFORM4UIVPROC) loader.load("glUniform4uiv");
        glTexParameterIiv = (PFNGLTEXPARAMETERIIVPROC) loader.load("glTexParameterIiv");
        glTexParameterIuiv = (PFNGLTEXPARAMETERIUIVPROC) loader.load("glTexParameterIuiv");
        glGetTexParameterIiv = (PFNGLGETTEXPARAMETERIIVPROC) loader.load("glGetTexParameterIiv");
        glGetTexParameterIuiv = (PFNGLGETTEXPARAMETERIUIVPROC) loader.load("glGetTexParameterIuiv");
        glClearBufferiv = (PFNGLCLEARBUFFERIVPROC) loader.load("glClearBufferiv");
        glClearBufferuiv = (PFNGLCLEARBUFFERUIVPROC) loader.load("glClearBufferuiv");
        glClearBufferfv = (PFNGLCLEARBUFFERFVPROC) loader.load("glClearBufferfv");
        glClearBufferfi = (PFNGLCLEARBUFFERFIPROC) loader.load("glClearBufferfi");
        glGetStringi = (PFNGLGETSTRINGIPROC) loader.load("glGetStringi");
        glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC) loader.load("glIsRenderbuffer");
        glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC) loader.load("glBindRenderbuffer");
        glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC) loader.load("glDeleteRenderbuffers");
        glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC) loader.load("glGenRenderbuffers");
        glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC) loader.load("glRenderbufferStorage");
        glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC) loader.load("glGetRenderbufferParameteriv");
        glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC) loader.load("glIsFramebuffer");
        glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC) loader.load("glBindFramebuffer");
        glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC) loader.load("glDeleteFramebuffers");
        glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC) loader.load("glGenFramebuffers");
        glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC) loader.load("glCheckFramebufferStatus");
        glFramebufferTexture1D = (PFNGLFRAMEBUFFERTEXTURE1DPROC) loader.load("glFramebufferTexture1D");
        glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC) loader.load("glFramebufferTexture2D");
        glFramebufferTexture3D = (PFNGLFRAMEBUFFERTEXTURE3DPROC) loader.load("glFramebufferTexture3D");
        glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC) loader.load("glFramebufferRenderbuffer");
        glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC) loader.load("glGetFramebufferAttachmentParameteriv");
        glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC) loader.load("glGenerateMipmap");
        glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC) loader.load("glBlitFramebuffer");
        glRenderbufferStorageMultisample = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC) loader.load("glRenderbufferStorageMultisample");
        glFramebufferTextureLayer = (PFNGLFRAMEBUFFERTEXTURELAYERPROC) loader.load("glFramebufferTextureLayer");
        glMapBufferRange = (PFNGLMAPBUFFERRANGEPROC) loader.load("glMapBufferRange");
        glFlushMappedBufferRange = (PFNGLFLUSHMAPPEDBUFFERRANGEPROC) loader.load("glFlushMappedBufferRange");
        glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC) loader.load("glBindVertexArray");
        glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC) loader.load("glDeleteVertexArrays");
        glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC) loader.load("glGenVertexArrays");
        glIsVertexArray = (PFNGLISVERTEXARRAYPROC) loader.load("glIsVertexArray");
    }
    if (version >= 31) {
        glDrawArraysInstanced = (PFNGLDRAWARRAYSINSTANCEDPROC) loader.load("glDrawArraysInstanced");
        glDrawElementsInstanced = (PFNGLDRAWELEMENTSINSTANCEDPROC) loader.load("glDrawElementsInstanced");
        glTexBuffer = (PFNGLTEXBUFFERPROC) loader.load("glTexBuffer");
        glPrimitiveRestartIndex = (PFNGLPRIMITIVERESTARTINDEXPROC) loader.load("glPrimitiveRestartIndex");
        glGetUniformIndices = (PFNGLGETUNIFORMINDICESPROC) loader.load("glGetUniformIndices");
        glGetActiveUniformsiv = (PFNGLGETACTIVEUNIFORMSIVPROC) loader.load("glGetActiveUniformsiv");
        glGetActiveUniformName = (PFNGLGETACTIVEUNIFORMNAMEPROC) loader.load("glGetActiveUniformName");
        glGetUniformBlockIndex = (PFNGLGETUNIFORMBLOCKINDEXPROC) loader.load("glGetUniformBlockIndex");
        glGetActiveUniformBlockiv = (PFNGLGETACTIVEUNIFORMBLOCKIVPROC) loader.load("glGetActiveUniformBlockiv");
        glGetActiveUniformBlockName = (PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC) loader.load("glGetActiveUniformBlockName");
        glUniformBlockBinding = (PFNGLUNIFORMBLOCKBINDINGPROC) loader.load("glUniformBlockBinding");
        glCopyBufferSubData = (PFNGLCOPYBUFFERSUBDATAPROC) loader.load("glCopyBufferSubData");
    }
    if (version >= 32) {
        glGetInteger64i_v = (PFNGLGETINTEGER64I_VPROC) loader.load("glGetInteger64i_v");
        glGetBufferParameteri64v = (PFNGLGETBUFFERPARAMETERI64VPROC) loader.load("glGetBufferParameteri64v");
        glFramebufferTexture = (PFNGLFRAMEBUFFERTEXTUREPROC) loader.load("glFramebufferTexture");
        glDrawElementsBaseVertex = (PFNGLDRAWELEMENTSBASEVERTEXPROC) loader.load("glDrawElementsBaseVertex");
        glDrawRangeElementsBaseVertex = (PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC) loader.load("glDrawRangeElementsBaseVertex");
        glDrawElementsInstancedBaseVertex = (PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC) loader.load("glDrawElementsInstancedBaseVertex");
        glMultiDrawElementsBaseVertex = (PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC) loader.load("glMultiDrawElementsBaseVertex");
        glProvokingVertex = (PFNGLPROVOKINGVERTEXPROC) loader.load("glProvokingVertex");
        glFenceSync = (PFNGLFENCESYNCPROC) loader.load("glFenceSync");
        glIsSync = (PFNGLISSYNCPROC) loader.load("glIsSync");
        glDeleteSync = (PFNGLDELETESYNCPROC) loader.load("glDeleteSync");
        glClientWaitSync = (PFNGLCLIENTWAITSYNCPROC) loader.load("glClientWaitSync");
        glWaitSync = (PFNGLWAITSYNCPROC) loader.load("glWaitSync");
        glGetInteger64v = (PFNGLGETINTEGER64VPROC) loader.load("glGetInteger64v");
        glGetSynciv = (PFNGLGETSYNCIVPROC) loader.load("glGetSynciv");
        glTexImage2DMultisample = (PFNGLTEXIMAGE2DMULTISAMPLEPROC) loader.load("glTexImage2DMultisample");
        glTexImage3DMultisample = (PFNGLTEXIMAGE3DMULTISAMPLEPROC) loader.load("glTexImage3DMultisample");
        glGetMultisamplefv = (PFNGLGETMULTISAMPLEFVPROC) loader.load("glGetMultisamplefv");
        glSampleMaski = (PFNGLSAMPLEMASKIPROC) loader.load("glSampleMaski");
    }
    if (version >= 33) {
        glVertexAttribDivisor = (PFNGLVERTEXATTRIBDIVISORPROC) loader.load("glVertexAttribDivisor");
        glBindFragDataLocationIndexed = (PFNGLBINDFRAGDATALOCATIONINDEXEDPROC) loader.load("glBindFragDataLocationIndexed");
        glGetFragDataIndex = (PFNGLGETFRAGDATAINDEXPROC) loader.load("glGetFragDataIndex");
        glGenSamplers = (PFNGLGENSAMPLERSPROC) loader.load("glGenSamplers");
        glDeleteSamplers = (PFNGLDELETESAMPLERSPROC) loader.load("glDeleteSamplers");
        glIsSampler = (PFNGLISSAMPLERPROC) loader.load("glIsSampler");
        glBindSampler = (PFNGLBINDSAMPLERPROC) loader.load("glBindSampler");
        glSamplerParameteri = (PFNGLSAMPLERPARAMETERIPROC) loader.load("glSamplerParameteri");
        glSamplerParameteriv = (PFNGLSAMPLERPARAMETERIVPROC) loader.load("glSamplerParameteriv");
        glSamplerParameterf = (PFNGLSAMPLERPARAMETERFPROC) loader.load("glSamplerParameterf");
        glSamplerParameterfv = (PFNGLSAMPLERPARAMETERFVPROC) loader.load("glSamplerParameterfv");
        glSamplerParameterIiv = (PFNGLSAMPLERPARAMETERIIVPROC) loader.load("glSamplerParameterIiv");
        glSamplerParameterIuiv = (PFNGLSAMPLERPARAMETERIUIVPROC) loader.load("glSamplerParameterIuiv");
        glGetSamplerParameteriv = (PFNGLGETSAMPLERPARAMETERIVPROC) loader.load("glGetSamplerParameteriv");
        glGetSamplerParameterIiv = (PFNGLGETSAMPLERPARAMETERIIVPROC) loader.load("glGetSamplerParameterIiv");
        glGetSamplerParameterfv = (PFNGLGETSAMPLERPARAMETERFVPROC) loader.load("glGetSamplerParameterfv");
        glGetSamplerParameterIuiv = (PFNGLGETSAMPLERPARAMETERIUIVPROC) loader.load("glGetSamplerParameterIuiv");
        glQueryCounter = (PFNGLQUERYCOUNTERPROC) loader.load("glQueryCounter");
        glGetQueryObjecti64v = (PFNGLGETQUERYOBJECTI64VPROC) loader.load("glGetQueryObjecti64v");
        glGetQueryObjectui64v = (PFNGLGETQUERYOBJECTUI64VPROC) loader.load("glGetQueryObjectui64v");
        glVertexP2ui = (PFNGLVERTEXP2UIPROC) loader.load("glVertexP2ui");
        glVertexP2uiv = (PFNGLVERTEXP2UIVPROC) loader.load("glVertexP2uiv");
        glVertexP3ui = (PFNGLVERTEXP3UIPROC) loader.load("glVertexP3ui");
        glVertexP3uiv = (PFNGLVERTEXP3UIVPROC) loader.load("glVertexP3uiv");
        glVertexP4ui = (PFNGLVERTEXP4UIPROC) loader.load("glVertexP4ui");
        glVertexP4uiv = (PFNGLVERTEXP4UIVPROC) loader.load("glVertexP4uiv");
        glTexCoordP1ui = (PFNGLTEXCOORDP1UIPROC) loader.load("glTexCoordP1ui");
        glTexCoordP1uiv = (PFNGLTEXCOORDP1UIVPROC) loader.load("glTexCoordP1uiv");
        glTexCoordP2ui = (PFNGLTEXCOORDP2UIPROC) loader.load("glTexCoordP2ui");
        glTexCoordP2uiv = (PFNGLTEXCOORDP2UIVPROC) loader.load("glTexCoordP2uiv");
        glTexCoordP3ui = (PFNGLTEXCOORDP3UIPROC) loader.load("glTexCoordP3ui");
        glTexCoordP3uiv = (PFNGLTEXCOORDP3UIVPROC) loader.load("glTexCoordP3uiv");
        glTexCoordP4ui = (PFNGLTEXCOORDP4UIPROC) loader.load("glTexCoordP4ui");
        glTexCoordP4uiv = (PFNGLTEXCOORDP4UIVPROC) loader.load("glTexCoordP4uiv");
        glMultiTexCoordP1ui = (PFNGLMULTITEXCOORDP1UIPROC) loader.load("glMultiTexCoordP1ui");
        glMultiTexCoordP1uiv = (PFNGLMULTITEXCOORDP1UIVPROC) loader.load("glMultiTexCoordP1uiv");
        glMultiTexCoordP2ui = (PFNGLMULTITEXCOORDP2UIPROC) loader.load("glMultiTexCoordP2ui");
        glMultiTexCoordP2uiv = (PFNGLMULTITEXCOORDP2UIVPROC) loader.load("glMultiTexCoordP2uiv");
        glMultiTexCoordP3ui = (PFNGLMULTITEXCOORDP3UIPROC) loader.load("glMultiTexCoordP3ui");
        glMultiTexCoordP3uiv = (PFNGLMULTITEXCOORDP3UIVPROC) loader.load("glMultiTexCoordP3uiv");
        glMultiTexCoordP4ui = (PFNGLMULTITEXCOORDP4UIPROC) loader.load("glMultiTexCoordP4ui");
        glMultiTexCoordP4uiv = (PFNGLMULTITEXCOORDP4UIVPROC) loader.load("glMultiTexCoordP4uiv");
        glNormalP3ui = (PFNGLNORMALP3UIPROC) loader.load("glNormalP3ui");
        glNormalP3uiv = (PFNGLNORMALP3UIVPROC) loader.load("glNormalP3uiv");
        glColorP3ui = (PFNGLCOLORP3UIPROC) loader.load("glColorP3ui");
        glColorP3uiv = (PFNGLCOLORP3UIVPROC) loader.load("glColorP3uiv");
        glColorP4ui = (PFNGLCOLORP4UIPROC) loader.load("glColorP4ui");
        glColorP4uiv = (PFNGLCOLORP4UIVPROC) loader.load("glColorP4uiv");
        glSecondaryColorP3ui = (PFNGLSECONDARYCOLORP3UIPROC) loader.load("glSecondaryColorP3ui");
        glSecondaryColorP3uiv = (PFNGLSECONDARYCOLORP3UIVPROC) loader.load("glSecondaryColorP3uiv");
        glVertexAttribP1ui = (PFNGLVERTEXATTRIBP1UIPROC) loader.load("glVertexAttribP1ui");
        glVertexAttribP1uiv = (PFNGLVERTEXATTRIBP1UIVPROC) loader.load("glVertexAttribP1uiv");
        glVertexAttribP2ui = (PFNGLVERTEXATTRIBP2UIPROC) loader.load("glVertexAttribP2ui");
        glVertexAttribP2uiv = (PFNGLVERTEXATTRIBP2UIVPROC) loader.load("glVertexAttribP2uiv");
        glVertexAttribP3ui = (PFNGLVERTEXATTRIBP3UIPROC) loader.load("glVertexAttribP3ui");
        glVertexAttribP3uiv = (PFNGLVERTEXATTRIBP3UIVPROC) loader.load("glVertexAttribP3uiv");
        glVertexAttribP4ui = (PFNGLVERTEXATTRIBP4UIPROC) loader.load("glVertexAttribP4ui");
        glVertexAttribP4uiv = (PFNGLVERTEXATTRIBP4UIVPROC) loader.load("glVertexAttribP4uiv");
    }
    if (version >= 40) {
        glMinSampleShading = (PFNGLMINSAMPLESHADINGPROC) loader.load("glMinSampleShading");
        glBlendEquationi = (PFNGLBLENDEQUATIONIPROC) loader.load("glBlendEquationi");
        glBlendEquationSeparatei = (PFNGLBLENDEQUATIONSEPARATEIPROC) loader.load("glBlendEquationSeparatei");
        glBlendFunci = (PFNGLBLENDFUNCIPROC) loader.load("glBlendFunci");
        glBlendFuncSeparatei = (PFNGLBLENDFUNCSEPARATEIPROC) loader.load("glBlendFuncSeparatei");
        glDrawArraysIndirect = (PFNGLDRAWARRAYSINDIRECTPROC) loader.load("glDrawArraysIndirect");
        glDrawElementsIndirect = (PFNGLDRAWELEMENTSINDIRECTPROC) loader.load("glDrawElementsIndirect");
        glUniform1d = (PFNGLUNIFORM1DPROC) loader.load("glUniform1d");
        glUniform2d = (PFNGLUNIFORM2DPROC) loader.load("glUniform2d");
        glUniform3d = (PFNGLUNIFORM3DPROC) loader.load("glUniform3d");
        glUniform4d = (PFNGLUNIFORM4DPROC) loader.load("glUniform4d");
        glUniform1dv = (PFNGLUNIFORM1DVPROC) loader.load("glUniform1dv");
        glUniform2dv = (PFNGLUNIFORM2DVPROC) loader.load("glUniform2dv");
        glUniform3dv = (PFNGLUNIFORM3DVPROC) loader.load("glUniform3dv");
        glUniform4dv = (PFNGLUNIFORM4DVPROC) loader.load("glUniform4dv");
        glUniformMatrix2dv = (PFNGLUNIFORMMATRIX2DVPROC) loader.load("glUniformMatrix2dv");
        glUniformMatrix3dv = (PFNGLUNIFORMMATRIX3DVPROC) loader.load("glUniformMatrix3dv");
        glUniformMatrix4dv = (PFNGLUNIFORMMATRIX4DVPROC) loader.load("glUniformMatrix4dv");
        glUniformMatrix2x3dv = (PFNGLUNIFORMMATRIX2X3DVPROC) loader.load("glUniformMatrix2x3dv");
        glUniformMatrix2x4dv = (PFNGLUNIFORMMATRIX2X4DVPROC) loader.load("glUniformMatrix2x4dv");
        glUniformMatrix3x2dv = (PFNGLUNIFORMMATRIX3X2DVPROC) loader.load("glUniformMatrix3x2dv");
        glUniformMatrix3x4dv = (PFNGLUNIFORMMATRIX3X4DVPROC) loader.load("glUniformMatrix3x4dv");
        glUniformMatrix4x2dv = (PFNGLUNIFORMMATRIX4X2DVPROC) loader.load("glUniformMatrix4x2dv");
        glUniformMatrix4x3dv = (PFNGLUNIFORMMATRIX4X3DVPROC) loader.load("glUniformMatrix4x3dv");
        glGetUniformdv = (PFNGLGETUNIFORMDVPROC) loader.load("glGetUniformdv");
        glGetSubroutineUniformLocation = (PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC) loader.load("glGetSubroutineUniformLocation");
        glGetSubroutineIndex = (PFNGLGETSUBROUTINEINDEXPROC) loader.load("glGetSubroutineIndex");
        glGetActiveSubroutineUniformiv = (PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC) loader.load("glGetActiveSubroutineUniformiv");
        glGetActiveSubroutineUniformName = (PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC) loader.load("glGetActiveSubroutineUniformName");
        glGetActiveSubroutineName = (PFNGLGETACTIVESUBROUTINENAMEPROC) loader.load("glGetActiveSubroutineName");
        glUniformSubroutinesuiv = (PFNGLUNIFORMSUBROUTINESUIVPROC) loader.load("glUniformSubroutinesuiv");
        glGetUniformSubroutineuiv = (PFNGLGETUNIFORMSUBROUTINEUIVPROC) loader.load("glGetUniformSubroutineuiv");
        glGetProgramStageiv = (PFNGLGETPROGRAMSTAGEIVPROC) loader.load("glGetProgramStageiv");
        glPatchParameteri = (PFNGLPATCHPARAMETERIPROC) loader.load("glPatchParameteri");
        glPatchParameterfv = (PFNGLPATCHPARAMETERFVPROC) loader.load("glPatchParameterfv");
        glBindTransformFeedback = (PFNGLBINDTRANSFORMFEEDBACKPROC) loader.load("glBindTransformFeedback");
        glDeleteTransformFeedbacks = (PFNGLDELETETRANSFORMFEEDBACKSPROC) loader.load("glDeleteTransformFeedbacks");
        glGenTransformFeedbacks = (PFNGLGENTRANSFORMFEEDBACKSPROC) loader.load("glGenTransformFeedbacks");
        glIsTransformFeedback = (PFNGLISTRANSFORMFEEDBACKPROC) loader.load("glIsTransformFeedback");
        glPauseTransformFeedback = (PFNGLPAUSETRANSFORMFEEDBACKPROC) loader.load("glPauseTransformFeedback");
        glResumeTransformFeedback = (PFNGLRESUMETRANSFORMFEEDBACKPROC) loader.load("glResumeTransformFeedback");
        glDrawTransformFeedback = (PFNGLDRAWTRANSFORMFEEDBACKPROC) loader.load("glDrawTransformFeedback");
        glDrawTransformFeedbackStream = (PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC) loader.load("glDrawTransformFeedbackStream");
        glBeginQueryIndexed = (PFNGLBEGINQUERYINDEXEDPROC) loader.load("glBeginQueryIndexed");
        glEndQueryIndexed = (PFNGLENDQUERYINDEXEDPROC) loader.load("glEndQueryIndexed");
        glGetQueryIndexediv = (PFNGLGETQUERYINDEXEDIVPROC) loader.load("glGetQueryIndexediv");
    }
    if (version >= 41) {
        glReleaseShaderCompiler = (PFNGLRELEASESHADERCOMPILERPROC) loader.load("glReleaseShaderCompiler");
        glShaderBinary = (PFNGLSHADERBINARYPROC) loader.load("glShaderBinary");
        glGetShaderPrecisionFormat = (PFNGLGETSHADERPRECISIONFORMATPROC) loader.load("glGetShaderPrecisionFormat");
        glDepthRangef = (PFNGLDEPTHRANGEFPROC) loader.load("glDepthRangef");
        glClearDepthf = (PFNGLCLEARDEPTHFPROC) loader.load("glClearDepthf");
        glGetProgramBinary = (PFNGLGETPROGRAMBINARYPROC) loader.load("glGetProgramBinary");
        glProgramBinary = (PFNGLPROGRAMBINARYPROC) loader.load("glProgramBinary");
        glProgramParameteri = (PFNGLPROGRAMPARAMETERIPROC) loader.load("glProgramParameteri");
        glUseProgramStages = (PFNGLUSEPROGRAMSTAGESPROC) loader.load("glUseProgramStages");
        glActiveShaderProgram = (PFNGLACTIVESHADERPROGRAMPROC) loader.load("glActiveShaderProgram");
        glCreateShaderProgramv = (PFNGLCREATESHADERPROGRAMVPROC) loader.load("glCreateShaderProgramv");
        glBindProgramPipeline = (PFNGLBINDPROGRAMPIPELINEPROC) loader.load("glBindProgramPipeline");
        glDeleteProgramPipelines = (PFNGLDELETEPROGRAMPIPELINESPROC) loader.load("glDeleteProgramPipelines");
        glGenProgramPipelines = (PFNGLGENPROGRAMPIPELINESPROC) loader.load("glGenProgramPipelines");
        glIsProgramPipeline = (PFNGLISPROGRAMPIPELINEPROC) loader.load("glIsProgramPipeline");
        glGetProgramPipelineiv = (PFNGLGETPROGRAMPIPELINEIVPROC) loader.load("glGetProgramPipelineiv");
        glProgramUniform1i = (PFNGLPROGRAMUNIFORM1IPROC) loader.load("glProgramUniform1i");
        glProgramUniform1iv = (PFNGLPROGRAMUNIFORM1IVPROC) loader.load("glProgramUniform1iv");
        glProgramUniform1f = (PFNGLPROGRAMUNIFORM1FPROC) loader.load("glProgramUniform1f");
        glProgramUniform1fv = (PFNGLPROGRAMUNIFORM1FVPROC) loader.load("glProgramUniform1fv");
        glProgramUniform1d = (PFNGLPROGRAMUNIFORM1DPROC) loader.load("glProgramUniform1d");
        glProgramUniform1dv = (PFNGLPROGRAMUNIFORM1DVPROC) loader.load("glProgramUniform1dv");
        glProgramUniform1ui = (PFNGLPROGRAMUNIFORM1UIPROC) loader.load("glProgramUniform1ui");
        glProgramUniform1uiv = (PFNGLPROGRAMUNIFORM1UIVPROC) loader.load("glProgramUniform1uiv");
        glProgramUniform2i = (PFNGLPROGRAMUNIFORM2IPROC) loader.load("glProgramUniform2i");
        glProgramUniform2iv = (PFNGLPROGRAMUNIFORM2IVPROC) loader.load("glProgramUniform2iv");
        glProgramUniform2f = (PFNGLPROGRAMUNIFORM2FPROC) loader.load("glProgramUniform2f");
        glProgramUniform2fv = (PFNGLPROGRAMUNIFORM2FVPROC) loader.load("glProgramUniform2fv");
        glProgramUniform2d = (PFNGLPROGRAMUNIFORM2DPROC) loader.load("glProgramUniform2d");
        glProgramUniform2dv = (PFNGLPROGRAMUNIFORM2DVPROC) loader.load("glProgramUniform2dv");
        glProgramUniform2ui = (PFNGLPROGRAMUNIFORM2UIPROC) loader.load("glProgramUniform2ui");
        glProgramUniform2uiv = (PFNGLPROGRAMUNIFORM2UIVPROC) loader.load("glProgramUniform2uiv");
        glProgramUniform3i = (PFNGLPROGRAMUNIFORM3IPROC) loader.load("glProgramUniform3i");
        glProgramUniform3iv = (PFNGLPROGRAMUNIFORM3IVPROC) loader.load("glProgramUniform3iv");
        glProgramUniform3f = (PFNGLPROGRAMUNIFORM3FPROC) loader.load("glProgramUniform3f");
        glProgramUniform3fv = (PFNGLPROGRAMUNIFORM3FVPROC) loader.load("glProgramUniform3fv");
        glProgramUniform3d = (PFNGLPROGRAMUNIFORM3DPROC) loader.load("glProgramUniform3d");
        glProgramUniform3dv = (PFNGLPROGRAMUNIFORM3DVPROC) loader.load("glProgramUniform3dv");
        glProgramUniform3ui = (PFNGLPROGRAMUNIFORM3UIPROC) loader.load("glProgramUniform3ui");
        glProgramUniform3uiv = (PFNGLPROGRAMUNIFORM3UIVPROC) loader.load("glProgramUniform3uiv");
        glProgramUniform4i = (PFNGLPROGRAMUNIFORM4IPROC) loader.load("glProgramUniform4i");
        glProgramUniform4iv = (PFNGLPROGRAMUNIFORM4IVPROC) loader.load("glProgramUniform4iv");
        glProgramUniform4f = (PFNGLPROGRAMUNIFORM4FPROC) loader.load("glProgramUniform4f");
        glProgramUniform4fv = (PFNGLPROGRAMUNIFORM4FVPROC) loader.load("glProgramUniform4fv");
        glProgramUniform4d = (PFNGLPROGRAMUNIFORM4DPROC) loader.load("glProgramUniform4d");
        glProgramUniform4dv = (PFNGLPROGRAMUNIFORM4DVPROC) loader.load("glProgramUniform4dv");
        glProgramUniform4ui = (PFNGLPROGRAMUNIFORM4UIPROC) loader.load("glProgramUniform4ui");
        glProgramUniform4uiv = (PFNGLPROGRAMUNIFORM4UIVPROC) loader.load("glProgramUniform4uiv");
        glProgramUniformMatrix2fv = (PFNGLPROGRAMUNIFORMMATRIX2FVPROC) loader.load("glProgramUniformMatrix2fv");
        glProgramUniformMatrix3fv = (PFNGLPROGRAMUNIFORMMATRIX3FVPROC) loader.load("glProgramUniformMatrix3fv");
        glProgramUniformMatrix4fv = (PFNGLPROGRAMUNIFORMMATRIX4FVPROC) loader.load("glProgramUniformMatrix4fv");
        glProgramUniformMatrix2dv = (PFNGLPROGRAMUNIFORMMATRIX2DVPROC) loader.load("glProgramUniformMatrix2dv");
        glProgramUniformMatrix3dv = (PFNGLPROGRAMUNIFORMMATRIX3DVPROC) loader.load("glProgramUniformMatrix3dv");
        glProgramUniformMatrix4dv = (PFNGLPROGRAMUNIFORMMATRIX4DVPROC) loader.load("glProgramUniformMatrix4dv");
        glProgramUniformMatrix2x3fv = (PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC) loader.load("glProgramUniformMatrix2x3fv");
        glProgramUniformMatrix3x2fv = (PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC) loader.load("glProgramUniformMatrix3x2fv");
        glProgramUniformMatrix2x4fv = (PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC) loader.load("glProgramUniformMatrix2x4fv");
        glProgramUniformMatrix4x2fv = (PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC) loader.load("glProgramUniformMatrix4x2fv");
        glProgramUniformMatrix3x4fv = (PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC) loader.load("glProgramUniformMatrix3x4fv");
        glProgramUniformMatrix4x3fv = (PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC) loader.load("glProgramUniformMatrix4x3fv");
        glProgramUniformMatrix2x3dv = (PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC) loader.load("glProgramUniformMatrix2x3dv");
        glProgramUniformMatrix3x2dv = (PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC) loader.load("glProgramUniformMatrix3x2dv");
        glProgramUniformMatrix2x4dv = (PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC) loader.load("glProgramUniformMatrix2x4dv");
        glProgramUniformMatrix4x2dv = (PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC) loader.load("glProgramUniformMatrix4x2dv");
        glProgramUniformMatrix3x4dv = (PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC) loader.load("glProgramUniformMatrix3x4dv");
        glProgramUniformMatrix4x3dv = (PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC) loader.load("glProgramUniformMatrix4x3dv");
        glValidateProgramPipeline = (PFNGLVALIDATEPROGRAMPIPELINEPROC) loader.load("glValidateProgramPipeline");
        glGetProgramPipelineInfoLog = (PFNGLGETPROGRAMPIPELINEINFOLOGPROC) loader.load("glGetProgramPipelineInfoLog");
        glVertexAttribL1d = (PFNGLVERTEXATTRIBL1DPROC) loader.load("glVertexAttribL1d");
        glVertexAttribL2d = (PFNGLVERTEXATTRIBL2DPROC) loader.load("glVertexAttribL2d");
        glVertexAttribL3d = (PFNGLVERTEXATTRIBL3DPROC) loader.load("glVertexAttribL3d");
        glVertexAttribL4d = (PFNGLVERTEXATTRIBL4DPROC) loader.load("glVertexAttribL4d");
        glVertexAttribL1dv = (PFNGLVERTEXATTRIBL1DVPROC) loader.load("glVertexAttribL1dv");
        glVertexAttribL2dv = (PFNGLVERTEXATTRIBL2DVPROC) loader.load("glVertexAttribL2dv");
        glVertexAttribL3dv = (PFNGLVERTEXATTRIBL3DVPROC) loader.load("glVertexAttribL3dv");
        glVertexAttribL4dv = (PFNGLVERTEXATTRIBL4DVPROC) loader.load("glVertexAttribL4dv");
        glVertexAttribLPointer = (PFNGLVERTEXATTRIBLPOINTERPROC) loader.load("glVertexAttribLPointer");
        glGetVertexAttribLdv = (PFNGLGETVERTEXATTRIBLDVPROC) loader.load("glGetVertexAttribLdv");
        glViewportArrayv = (PFNGLVIEWPORTARRAYVPROC) loader.load("glViewportArrayv");
        glViewportIndexedf = (PFNGLVIEWPORTINDEXEDFPROC) loader.load("glViewportIndexedf");
        glViewportIndexedfv = (PFNGLVIEWPORTINDEXEDFVPROC) loader.load("glViewportIndexedfv");
        glScissorArrayv = (PFNGLSCISSORARRAYVPROC) loader.load("glScissorArrayv");
        glScissorIndexed = (PFNGLSCISSORINDEXEDPROC) loader.load("glScissorIndexed");
        glScissorIndexedv = (PFNGLSCISSORINDEXEDVPROC) loader.load("glScissorIndexedv");
        glDepthRangeArrayv = (PFNGLDEPTHRANGEARRAYVPROC) loader.load("glDepthRangeArrayv");
        glDepthRangeIndexed = (PFNGLDEPTHRANGEINDEXEDPROC) loader.load("glDepthRangeIndexed");
        glGetFloati_v = (PFNGLGETFLOATI_VPROC) loader.load("glGetFloati_v");
        glGetDoublei_v = (PFNGLGETDOUBLEI_VPROC) loader.load("glGetDoublei_v");
    }

	loader.formatter.allocator.reset();
	core::bufferStringStream::printf(loader.formatter,"OpenGL %d.%d core was loaded!",loader.major,loader.minor);
	services::logging()->information(core::bufferStringStream::asCString(loader.formatter));
}

#undef F

//opengl functions
#define extern

#ifndef ARPHEG_PLATFORM_WIN32

/*extern PFNGLCULLFACEPROC glCullFace;
extern PFNGLFRONTFACEPROC glFrontFace;
extern PFNGLHINTPROC glHint;
extern PFNGLLINEWIDTHPROC glLineWidth;
extern PFNGLPOINTSIZEPROC glPointSize;
extern PFNGLPOLYGONMODEPROC glPolygonMode;
extern PFNGLSCISSORPROC glScissor;
extern PFNGLTEXPARAMETERFPROC glTexParameterf;
extern PFNGLTEXPARAMETERFVPROC glTexParameterfv;
extern PFNGLTEXPARAMETERIPROC glTexParameteri;
extern PFNGLTEXPARAMETERIVPROC glTexParameteriv;
extern PFNGLTEXIMAGE1DPROC glTexImage1D;
extern PFNGLTEXIMAGE2DPROC glTexImage2D;
extern PFNGLDRAWBUFFERPROC glDrawBuffer;
extern PFNGLCLEARPROC glClear;
extern PFNGLCLEARCOLORPROC glClearColor;
extern PFNGLCLEARSTENCILPROC glClearStencil;
extern PFNGLCLEARDEPTHPROC glClearDepth;
extern PFNGLSTENCILMASKPROC glStencilMask;
extern PFNGLCOLORMASKPROC glColorMask;
extern PFNGLDEPTHMASKPROC glDepthMask;
extern PFNGLDISABLEPROC glDisable;
extern PFNGLENABLEPROC glEnable;
extern PFNGLFINISHPROC glFinish;
extern PFNGLFLUSHPROC glFlush;
extern PFNGLBLENDFUNCPROC glBlendFunc;
extern PFNGLLOGICOPPROC glLogicOp;
extern PFNGLSTENCILFUNCPROC glStencilFunc;
extern PFNGLSTENCILOPPROC glStencilOp;
extern PFNGLDEPTHFUNCPROC glDepthFunc;
extern PFNGLPIXELSTOREFPROC glPixelStoref;
extern PFNGLPIXELSTOREIPROC glPixelStorei;
extern PFNGLREADBUFFERPROC glReadBuffer;
extern PFNGLREADPIXELSPROC glReadPixels;
extern PFNGLGETBOOLEANVPROC glGetBooleanv;
extern PFNGLGETDOUBLEVPROC glGetDoublev;
extern PFNGLGETERRORPROC glGetError;
extern PFNGLGETFLOATVPROC glGetFloatv;
extern PFNGLGETINTEGERVPROC glGetIntegerv;
extern PFNGLGETSTRINGPROC glGetString;
extern PFNGLGETTEXIMAGEPROC glGetTexImage;
extern PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv;
extern PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv;
extern PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv;
extern PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv;
extern PFNGLISENABLEDPROC glIsEnabled;
extern PFNGLDEPTHRANGEPROC glDepthRange;
extern PFNGLVIEWPORTPROC glViewport;
extern PFNGLDRAWARRAYSPROC glDrawArrays;
extern PFNGLDRAWELEMENTSPROC glDrawElements;
extern PFNGLGETPOINTERVPROC glGetPointerv;
extern PFNGLPOLYGONOFFSETPROC glPolygonOffset;
extern PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D;
extern PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D;
extern PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D;
extern PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D;
extern PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D;
extern PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D;
extern PFNGLBINDTEXTUREPROC glBindTexture;
extern PFNGLDELETETEXTURESPROC glDeleteTextures;
extern PFNGLGENTEXTURESPROC glGenTextures;
extern PFNGLISTEXTUREPROC glIsTexture;*/

#endif

extern PFNGLBLENDCOLORPROC glBlendColor;
extern PFNGLBLENDEQUATIONPROC glBlendEquation;
extern PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements;
extern PFNGLTEXIMAGE3DPROC glTexImage3D;
extern PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D;
extern PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D;
extern PFNGLACTIVETEXTUREPROC glActiveTexture;
extern PFNGLSAMPLECOVERAGEPROC glSampleCoverage;
extern PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D;
extern PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;
extern PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D;
extern PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D;
extern PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage;
extern PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
extern PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays;
extern PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements;
extern PFNGLPOINTPARAMETERFPROC glPointParameterf;
extern PFNGLPOINTPARAMETERFVPROC glPointParameterfv;
extern PFNGLPOINTPARAMETERIPROC glPointParameteri;
extern PFNGLPOINTPARAMETERIVPROC glPointParameteriv;
extern PFNGLGENQUERIESPROC glGenQueries;
extern PFNGLDELETEQUERIESPROC glDeleteQueries;
extern PFNGLISQUERYPROC glIsQuery;
extern PFNGLBEGINQUERYPROC glBeginQuery;
extern PFNGLENDQUERYPROC glEndQuery;
extern PFNGLGETQUERYIVPROC glGetQueryiv;
extern PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv;
extern PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv;
extern PFNGLBINDBUFFERPROC glBindBuffer;
extern PFNGLDELETEBUFFERSPROC glDeleteBuffers;
extern PFNGLGENBUFFERSPROC glGenBuffers;
extern PFNGLISBUFFERPROC glIsBuffer;
extern PFNGLBUFFERDATAPROC glBufferData;
extern PFNGLBUFFERSUBDATAPROC glBufferSubData;
extern PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData;
extern PFNGLMAPBUFFERPROC glMapBuffer;
extern PFNGLUNMAPBUFFERPROC glUnmapBuffer;
extern PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
extern PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv;
extern PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
extern PFNGLDRAWBUFFERSPROC glDrawBuffers;
extern PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate;
extern PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate;
extern PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate;
extern PFNGLATTACHSHADERPROC glAttachShader;
extern PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
extern PFNGLCOMPILESHADERPROC glCompileShader;
extern PFNGLCREATEPROGRAMPROC glCreateProgram;
extern PFNGLCREATESHADERPROC glCreateShader;
extern PFNGLDELETEPROGRAMPROC glDeleteProgram;
extern PFNGLDELETESHADERPROC glDeleteShader;
extern PFNGLDETACHSHADERPROC glDetachShader;
extern PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
extern PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
extern PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib;
extern PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform;
extern PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders;
extern PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
extern PFNGLGETPROGRAMIVPROC glGetProgramiv;
extern PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
extern PFNGLGETSHADERIVPROC glGetShaderiv;
extern PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
extern PFNGLGETSHADERSOURCEPROC glGetShaderSource;
extern PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
extern PFNGLGETUNIFORMFVPROC glGetUniformfv;
extern PFNGLGETUNIFORMIVPROC glGetUniformiv;
extern PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv;
extern PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
extern PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
extern PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv;
extern PFNGLISPROGRAMPROC glIsProgram;
extern PFNGLISSHADERPROC glIsShader;
extern PFNGLLINKPROGRAMPROC glLinkProgram;
extern PFNGLSHADERSOURCEPROC glShaderSource;
extern PFNGLUSEPROGRAMPROC glUseProgram;
extern PFNGLUNIFORM1FPROC glUniform1f;
extern PFNGLUNIFORM2FPROC glUniform2f;
extern PFNGLUNIFORM3FPROC glUniform3f;
extern PFNGLUNIFORM4FPROC glUniform4f;
extern PFNGLUNIFORM1IPROC glUniform1i;
extern PFNGLUNIFORM2IPROC glUniform2i;
extern PFNGLUNIFORM3IPROC glUniform3i;
extern PFNGLUNIFORM4IPROC glUniform4i;
extern PFNGLUNIFORM1FVPROC glUniform1fv;
extern PFNGLUNIFORM2FVPROC glUniform2fv;
extern PFNGLUNIFORM3FVPROC glUniform3fv;
extern PFNGLUNIFORM4FVPROC glUniform4fv;
extern PFNGLUNIFORM1IVPROC glUniform1iv;
extern PFNGLUNIFORM2IVPROC glUniform2iv;
extern PFNGLUNIFORM3IVPROC glUniform3iv;
extern PFNGLUNIFORM4IVPROC glUniform4iv;
extern PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
extern PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
extern PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
extern PFNGLVALIDATEPROGRAMPROC glValidateProgram;
extern PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d;
extern PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv;
extern PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f;
extern PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv;
extern PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s;
extern PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv;
extern PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d;
extern PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv;
extern PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f;
extern PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv;
extern PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s;
extern PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv;
extern PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d;
extern PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv;
extern PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f;
extern PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv;
extern PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s;
extern PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv;
extern PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv;
extern PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv;
extern PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv;
extern PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub;
extern PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv;
extern PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv;
extern PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv;
extern PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv;
extern PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d;
extern PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv;
extern PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f;
extern PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;
extern PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv;
extern PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s;
extern PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv;
extern PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv;
extern PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv;
extern PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv;
extern PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
extern PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv;
extern PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv;
extern PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv;
extern PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv;
extern PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv;
extern PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv;
extern PFNGLCOLORMASKIPROC glColorMaski;
extern PFNGLGETBOOLEANI_VPROC glGetBooleani_v;
extern PFNGLGETINTEGERI_VPROC glGetIntegeri_v;
extern PFNGLENABLEIPROC glEnablei;
extern PFNGLDISABLEIPROC glDisablei;
extern PFNGLISENABLEDIPROC glIsEnabledi;
extern PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback;
extern PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback;
extern PFNGLBINDBUFFERRANGEPROC glBindBufferRange;
extern PFNGLBINDBUFFERBASEPROC glBindBufferBase;
extern PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings;
extern PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying;
extern PFNGLCLAMPCOLORPROC glClampColor;
extern PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender;
extern PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender;
extern PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer;
extern PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv;
extern PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv;
extern PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i;
extern PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i;
extern PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i;
extern PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i;
extern PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui;
extern PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui;
extern PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui;
extern PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui;
extern PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv;
extern PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv;
extern PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv;
extern PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv;
extern PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv;
extern PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv;
extern PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv;
extern PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv;
extern PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv;
extern PFNGLVERTEXATTRIBI4SVPROC glVertexAttribI4sv;
extern PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv;
extern PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv;
extern PFNGLGETUNIFORMUIVPROC glGetUniformuiv;
extern PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation;
extern PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation;
extern PFNGLUNIFORM1UIPROC glUniform1ui;
extern PFNGLUNIFORM2UIPROC glUniform2ui;
extern PFNGLUNIFORM3UIPROC glUniform3ui;
extern PFNGLUNIFORM4UIPROC glUniform4ui;
extern PFNGLUNIFORM1UIVPROC glUniform1uiv;
extern PFNGLUNIFORM2UIVPROC glUniform2uiv;
extern PFNGLUNIFORM3UIVPROC glUniform3uiv;
extern PFNGLUNIFORM4UIVPROC glUniform4uiv;
extern PFNGLTEXPARAMETERIIVPROC glTexParameterIiv;
extern PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv;
extern PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv;
extern PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv;
extern PFNGLCLEARBUFFERIVPROC glClearBufferiv;
extern PFNGLCLEARBUFFERUIVPROC glClearBufferuiv;
extern PFNGLCLEARBUFFERFVPROC glClearBufferfv;
extern PFNGLCLEARBUFFERFIPROC glClearBufferfi;
extern PFNGLGETSTRINGIPROC glGetStringi;
extern PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
extern PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;
extern PFNGLTEXBUFFERPROC glTexBuffer;
extern PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex;
extern PFNGLGETINTEGER64I_VPROC glGetInteger64i_v;
extern PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v;
extern PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture;
extern PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor;
extern PFNGLMINSAMPLESHADINGPROC glMinSampleShading;
extern PFNGLBLENDEQUATIONIPROC glBlendEquationi;
extern PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei;
extern PFNGLBLENDFUNCIPROC glBlendFunci;
extern PFNGLBLENDFUNCSEPARATEIPROC glBlendFuncSeparatei;
extern PFNGLISRENDERBUFFERPROC glIsRenderbuffer;
extern PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
extern PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
extern PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
extern PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
extern PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;
extern PFNGLISFRAMEBUFFERPROC glIsFramebuffer;
extern PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
extern PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
extern PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
extern PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
extern PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D;
extern PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
extern PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D;
extern PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
extern PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;
extern PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
extern PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer;
extern PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample;
extern PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer;
extern PFNGLMAPBUFFERRANGEPROC glMapBufferRange;
extern PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange;
extern PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
extern PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
extern PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
extern PFNGLISVERTEXARRAYPROC glIsVertexArray;
extern PFNGLGETUNIFORMINDICESPROC glGetUniformIndices;
extern PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv;
extern PFNGLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName;
extern PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex;
extern PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv;
extern PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName;
extern PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding;
extern PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData;
extern PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex;
extern PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex;
extern PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex;
extern PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex;
extern PFNGLPROVOKINGVERTEXPROC glProvokingVertex;
extern PFNGLFENCESYNCPROC glFenceSync;
extern PFNGLISSYNCPROC glIsSync;
extern PFNGLDELETESYNCPROC glDeleteSync;
extern PFNGLCLIENTWAITSYNCPROC glClientWaitSync;
extern PFNGLWAITSYNCPROC glWaitSync;
extern PFNGLGETINTEGER64VPROC glGetInteger64v;
extern PFNGLGETSYNCIVPROC glGetSynciv;
extern PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample;
extern PFNGLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample;
extern PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv;
extern PFNGLSAMPLEMASKIPROC glSampleMaski;
extern PFNGLBLENDEQUATIONIARBPROC glBlendEquationiARB;
extern PFNGLBLENDEQUATIONSEPARATEIARBPROC glBlendEquationSeparateiARB;
extern PFNGLBLENDFUNCIARBPROC glBlendFunciARB;
extern PFNGLBLENDFUNCSEPARATEIARBPROC glBlendFuncSeparateiARB;
extern PFNGLMINSAMPLESHADINGARBPROC glMinSampleShadingARB;
extern PFNGLNAMEDSTRINGARBPROC glNamedStringARB;
extern PFNGLDELETENAMEDSTRINGARBPROC glDeleteNamedStringARB;
extern PFNGLCOMPILESHADERINCLUDEARBPROC glCompileShaderIncludeARB;
extern PFNGLISNAMEDSTRINGARBPROC glIsNamedStringARB;
extern PFNGLGETNAMEDSTRINGARBPROC glGetNamedStringARB;
extern PFNGLGETNAMEDSTRINGIVARBPROC glGetNamedStringivARB;
extern PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed;
extern PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex;
extern PFNGLGENSAMPLERSPROC glGenSamplers;
extern PFNGLDELETESAMPLERSPROC glDeleteSamplers;
extern PFNGLISSAMPLERPROC glIsSampler;
extern PFNGLBINDSAMPLERPROC glBindSampler;
extern PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri;
extern PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv;
extern PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf;
extern PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv;
extern PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv;
extern PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv;
extern PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv;
extern PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv;
extern PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv;
extern PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv;
extern PFNGLQUERYCOUNTERPROC glQueryCounter;
extern PFNGLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v;
extern PFNGLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v;
extern PFNGLVERTEXP2UIPROC glVertexP2ui;
extern PFNGLVERTEXP2UIVPROC glVertexP2uiv;
extern PFNGLVERTEXP3UIPROC glVertexP3ui;
extern PFNGLVERTEXP3UIVPROC glVertexP3uiv;
extern PFNGLVERTEXP4UIPROC glVertexP4ui;
extern PFNGLVERTEXP4UIVPROC glVertexP4uiv;
extern PFNGLTEXCOORDP1UIPROC glTexCoordP1ui;
extern PFNGLTEXCOORDP1UIVPROC glTexCoordP1uiv;
extern PFNGLTEXCOORDP2UIPROC glTexCoordP2ui;
extern PFNGLTEXCOORDP2UIVPROC glTexCoordP2uiv;
extern PFNGLTEXCOORDP3UIPROC glTexCoordP3ui;
extern PFNGLTEXCOORDP3UIVPROC glTexCoordP3uiv;
extern PFNGLTEXCOORDP4UIPROC glTexCoordP4ui;
extern PFNGLTEXCOORDP4UIVPROC glTexCoordP4uiv;
extern PFNGLMULTITEXCOORDP1UIPROC glMultiTexCoordP1ui;
extern PFNGLMULTITEXCOORDP1UIVPROC glMultiTexCoordP1uiv;
extern PFNGLMULTITEXCOORDP2UIPROC glMultiTexCoordP2ui;
extern PFNGLMULTITEXCOORDP2UIVPROC glMultiTexCoordP2uiv;
extern PFNGLMULTITEXCOORDP3UIPROC glMultiTexCoordP3ui;
extern PFNGLMULTITEXCOORDP3UIVPROC glMultiTexCoordP3uiv;
extern PFNGLMULTITEXCOORDP4UIPROC glMultiTexCoordP4ui;
extern PFNGLMULTITEXCOORDP4UIVPROC glMultiTexCoordP4uiv;
extern PFNGLNORMALP3UIPROC glNormalP3ui;
extern PFNGLNORMALP3UIVPROC glNormalP3uiv;
extern PFNGLCOLORP3UIPROC glColorP3ui;
extern PFNGLCOLORP3UIVPROC glColorP3uiv;
extern PFNGLCOLORP4UIPROC glColorP4ui;
extern PFNGLCOLORP4UIVPROC glColorP4uiv;
extern PFNGLSECONDARYCOLORP3UIPROC glSecondaryColorP3ui;
extern PFNGLSECONDARYCOLORP3UIVPROC glSecondaryColorP3uiv;
extern PFNGLVERTEXATTRIBP1UIPROC glVertexAttribP1ui;
extern PFNGLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv;
extern PFNGLVERTEXATTRIBP2UIPROC glVertexAttribP2ui;
extern PFNGLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv;
extern PFNGLVERTEXATTRIBP3UIPROC glVertexAttribP3ui;
extern PFNGLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv;
extern PFNGLVERTEXATTRIBP4UIPROC glVertexAttribP4ui;
extern PFNGLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv;
extern PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect;
extern PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect;
extern PFNGLUNIFORM1DPROC glUniform1d;
extern PFNGLUNIFORM2DPROC glUniform2d;
extern PFNGLUNIFORM3DPROC glUniform3d;
extern PFNGLUNIFORM4DPROC glUniform4d;
extern PFNGLUNIFORM1DVPROC glUniform1dv;
extern PFNGLUNIFORM2DVPROC glUniform2dv;
extern PFNGLUNIFORM3DVPROC glUniform3dv;
extern PFNGLUNIFORM4DVPROC glUniform4dv;
extern PFNGLUNIFORMMATRIX2DVPROC glUniformMatrix2dv;
extern PFNGLUNIFORMMATRIX3DVPROC glUniformMatrix3dv;
extern PFNGLUNIFORMMATRIX4DVPROC glUniformMatrix4dv;
extern PFNGLUNIFORMMATRIX2X3DVPROC glUniformMatrix2x3dv;
extern PFNGLUNIFORMMATRIX2X4DVPROC glUniformMatrix2x4dv;
extern PFNGLUNIFORMMATRIX3X2DVPROC glUniformMatrix3x2dv;
extern PFNGLUNIFORMMATRIX3X4DVPROC glUniformMatrix3x4dv;
extern PFNGLUNIFORMMATRIX4X2DVPROC glUniformMatrix4x2dv;
extern PFNGLUNIFORMMATRIX4X3DVPROC glUniformMatrix4x3dv;
extern PFNGLGETUNIFORMDVPROC glGetUniformdv;
extern PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC glGetSubroutineUniformLocation;
extern PFNGLGETSUBROUTINEINDEXPROC glGetSubroutineIndex;
extern PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC glGetActiveSubroutineUniformiv;
extern PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC glGetActiveSubroutineUniformName;
extern PFNGLGETACTIVESUBROUTINENAMEPROC glGetActiveSubroutineName;
extern PFNGLUNIFORMSUBROUTINESUIVPROC glUniformSubroutinesuiv;
extern PFNGLGETUNIFORMSUBROUTINEUIVPROC glGetUniformSubroutineuiv;
extern PFNGLGETPROGRAMSTAGEIVPROC glGetProgramStageiv;
extern PFNGLPATCHPARAMETERIPROC glPatchParameteri;
extern PFNGLPATCHPARAMETERFVPROC glPatchParameterfv;
extern PFNGLBINDTRANSFORMFEEDBACKPROC glBindTransformFeedback;
extern PFNGLDELETETRANSFORMFEEDBACKSPROC glDeleteTransformFeedbacks;
extern PFNGLGENTRANSFORMFEEDBACKSPROC glGenTransformFeedbacks;
extern PFNGLISTRANSFORMFEEDBACKPROC glIsTransformFeedback;
extern PFNGLPAUSETRANSFORMFEEDBACKPROC glPauseTransformFeedback;
extern PFNGLRESUMETRANSFORMFEEDBACKPROC glResumeTransformFeedback;
extern PFNGLDRAWTRANSFORMFEEDBACKPROC glDrawTransformFeedback;
extern PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC glDrawTransformFeedbackStream;
extern PFNGLBEGINQUERYINDEXEDPROC glBeginQueryIndexed;
extern PFNGLENDQUERYINDEXEDPROC glEndQueryIndexed;
extern PFNGLGETQUERYINDEXEDIVPROC glGetQueryIndexediv;
extern PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler;
extern PFNGLSHADERBINARYPROC glShaderBinary;
extern PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat;
extern PFNGLDEPTHRANGEFPROC glDepthRangef;
extern PFNGLCLEARDEPTHFPROC glClearDepthf;
extern PFNGLGETPROGRAMBINARYPROC glGetProgramBinary;
extern PFNGLPROGRAMBINARYPROC glProgramBinary;
extern PFNGLPROGRAMPARAMETERIPROC glProgramParameteri;
extern PFNGLUSEPROGRAMSTAGESPROC glUseProgramStages;
extern PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram;
extern PFNGLCREATESHADERPROGRAMVPROC glCreateShaderProgramv;
extern PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline;
extern PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines;
extern PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines;
extern PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline;
extern PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv;
extern PFNGLPROGRAMUNIFORM1IPROC glProgramUniform1i;
extern PFNGLPROGRAMUNIFORM1IVPROC glProgramUniform1iv;
extern PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f;
extern PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv;
extern PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d;
extern PFNGLPROGRAMUNIFORM1DVPROC glProgramUniform1dv;
extern PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui;
extern PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv;
extern PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i;
extern PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv;
extern PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f;
extern PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv;
extern PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d;
extern PFNGLPROGRAMUNIFORM2DVPROC glProgramUniform2dv;
extern PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui;
extern PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv;
extern PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i;
extern PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv;
extern PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f;
extern PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv;
extern PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d;
extern PFNGLPROGRAMUNIFORM3DVPROC glProgramUniform3dv;
extern PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui;
extern PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv;
extern PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i;
extern PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv;
extern PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f;
extern PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv;
extern PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d;
extern PFNGLPROGRAMUNIFORM4DVPROC glProgramUniform4dv;
extern PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui;
extern PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv;
extern PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv;
extern PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv;
extern PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv;
extern PFNGLPROGRAMUNIFORMMATRIX2DVPROC glProgramUniformMatrix2dv;
extern PFNGLPROGRAMUNIFORMMATRIX3DVPROC glProgramUniformMatrix3dv;
extern PFNGLPROGRAMUNIFORMMATRIX4DVPROC glProgramUniformMatrix4dv;
extern PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv;
extern PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv;
extern PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv;
extern PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv;
extern PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv;
extern PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv;
extern PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glProgramUniformMatrix2x3dv;
extern PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glProgramUniformMatrix3x2dv;
extern PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glProgramUniformMatrix2x4dv;
extern PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glProgramUniformMatrix4x2dv;
extern PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glProgramUniformMatrix3x4dv;
extern PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glProgramUniformMatrix4x3dv;
extern PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline;
extern PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog;
extern PFNGLVERTEXATTRIBL1DPROC glVertexAttribL1d;
extern PFNGLVERTEXATTRIBL2DPROC glVertexAttribL2d;
extern PFNGLVERTEXATTRIBL3DPROC glVertexAttribL3d;
extern PFNGLVERTEXATTRIBL4DPROC glVertexAttribL4d;
extern PFNGLVERTEXATTRIBL1DVPROC glVertexAttribL1dv;
extern PFNGLVERTEXATTRIBL2DVPROC glVertexAttribL2dv;
extern PFNGLVERTEXATTRIBL3DVPROC glVertexAttribL3dv;
extern PFNGLVERTEXATTRIBL4DVPROC glVertexAttribL4dv;
extern PFNGLVERTEXATTRIBLPOINTERPROC glVertexAttribLPointer;
extern PFNGLGETVERTEXATTRIBLDVPROC glGetVertexAttribLdv;
extern PFNGLVIEWPORTARRAYVPROC glViewportArrayv;
extern PFNGLVIEWPORTINDEXEDFPROC glViewportIndexedf;
extern PFNGLVIEWPORTINDEXEDFVPROC glViewportIndexedfv;
extern PFNGLSCISSORARRAYVPROC glScissorArrayv;
extern PFNGLSCISSORINDEXEDPROC glScissorIndexed;
extern PFNGLSCISSORINDEXEDVPROC glScissorIndexedv;
extern PFNGLDEPTHRANGEARRAYVPROC glDepthRangeArrayv;
extern PFNGLDEPTHRANGEINDEXEDPROC glDepthRangeIndexed;
extern PFNGLGETFLOATI_VPROC glGetFloati_v;
extern PFNGLGETDOUBLEI_VPROC glGetDoublei_v;
extern PFNGLCREATESYNCFROMCLEVENTARBPROC glCreateSyncFromCLeventARB;
extern PFNGLDEBUGMESSAGECONTROLARBPROC glDebugMessageControlARB;
extern PFNGLDEBUGMESSAGEINSERTARBPROC glDebugMessageInsertARB;
extern PFNGLDEBUGMESSAGECALLBACKARBPROC glDebugMessageCallbackARB;
extern PFNGLGETDEBUGMESSAGELOGARBPROC glGetDebugMessageLogARB;
extern PFNGLGETGRAPHICSRESETSTATUSARBPROC glGetGraphicsResetStatusARB;
extern PFNGLGETNMAPDVARBPROC glGetnMapdvARB;
extern PFNGLGETNMAPFVARBPROC glGetnMapfvARB;
extern PFNGLGETNMAPIVARBPROC glGetnMapivARB;
extern PFNGLGETNPIXELMAPFVARBPROC glGetnPixelMapfvARB;
extern PFNGLGETNPIXELMAPUIVARBPROC glGetnPixelMapuivARB;
extern PFNGLGETNPIXELMAPUSVARBPROC glGetnPixelMapusvARB;
extern PFNGLGETNPOLYGONSTIPPLEARBPROC glGetnPolygonStippleARB;
extern PFNGLGETNCOLORTABLEARBPROC glGetnColorTableARB;
extern PFNGLGETNCONVOLUTIONFILTERARBPROC glGetnConvolutionFilterARB;
extern PFNGLGETNSEPARABLEFILTERARBPROC glGetnSeparableFilterARB;
extern PFNGLGETNHISTOGRAMARBPROC glGetnHistogramARB;
extern PFNGLGETNMINMAXARBPROC glGetnMinmaxARB;
extern PFNGLGETNTEXIMAGEARBPROC glGetnTexImageARB;
extern PFNGLREADNPIXELSARBPROC glReadnPixelsARB;
extern PFNGLGETNCOMPRESSEDTEXIMAGEARBPROC glGetnCompressedTexImageARB;
extern PFNGLGETNUNIFORMFVARBPROC glGetnUniformfvARB;
extern PFNGLGETNUNIFORMIVARBPROC glGetnUniformivARB;
extern PFNGLGETNUNIFORMUIVARBPROC glGetnUniformuivARB;
extern PFNGLGETNUNIFORMDVARBPROC glGetnUniformdvARB;

#undef extern

#endif
